### ISSUE TITLE
The app don't load the database

### ISSUE THREAD

**Issue by Jovisx** [ALEEF02/Bulletin-Magazine-Mobile-App#9]
I think after the new Firebase upgrade the app don't work and need some change in the code, I'll try to fix this error

**Comment by ALEEF02** [comment]
Thanks! Quick question, how did you find this repository?

**Comment by Jovisx** [comment]
I was just looking around and I see it, I tested the app a few days ago and all works fine, but after 2 days the app didn’t show anymore the pdf, I think it is because the new firebase update, did you have the same error guys?
